"""add_source_details

Revision ID: 8fa321b4b617
Revises: 90fd508fad86
Create Date: 2025-11-20 01:01:23.911166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa321b4b617'
down_revision: Union[str, Sequence[str], None] = '90fd508fad86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed entities alterations as they are not supported/needed for this task and cause SQLite errors
    op.add_column('sources', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('founded_at', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('hq_location', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('bias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'bias')
    op.drop_column('sources', 'hq_location')
    op.drop_column('sources', 'founded_at')
    op.drop_column('sources', 'owner')
    # Removed entities alterations
    # ### end Alembic commands ###
